#!/usr/bin/env node
const fs = require('fs');
const http = require('http');
const path = require('path');
const express = require('express');
const bodyParser = require('body-parser');
const app = express();
const cors = require('express-cors');

// bodyParser needed to parse POST form data
app.use(bodyParser.urlencoded({extended: true}));

app.use(cors({
  headers: ['X-Requested-With', 'Content-Type', 'Custom-FormNick'],
  allowedOrigins: ['127.0.0.1:*', 'localhost:*']
}));

app.get('/', (req, res) => res.send('This is a dev server used for the Angular 2 examples'));
app.get('/data', getData);
app.get('/uk/rss/topsongs/limit=100/json', getTop100);
app.post('/data', (req, res) => {
  return res.send({well:'done'});
});
app.post('/login', (req, res) => res.json(JSON.stringify({reason: 'I got ya bro'})));

// const server = app.listen(1970, () => console.log('Server running at http://localhost:' + server.address().port));
const server = http.createServer(app);


const io = require('socket.io')(server);
io.on('connection', function (socket) {
  socket.emit('msg', {msg: 'Welcome To the Socket Server!!!'});
  socket.on('msg', function (msg) {
    socket.emit('msg', {msg: "you sent : " + msg});
  })
});

server.listen(1970, () => console.log('Server running at http://localhost:' + server.address().port));


function getData(req, res) {
  const json = path.join(__dirname, '../src/json/characters.json');
  const readable = fs.createReadStream(json);
  readable.pipe(res);
}


function getTop100(req, res) {
  const top100itunesFile = path.join(__dirname, '../src/assets/json/top100itunes.json');
  fs.readFile(top100itunesFile, (err, data) => {
    if (err) {
      console.error(err);
      process.exit(1);
    }
    let results = parseInt(req.query.results, 10);
    if (isNaN(results)) {
      results = 100;
    }
    data = JSON.parse(data);
    data.feed.entry = data.feed.entry.slice(0, results);
    res.json(data);
  });
}

app.use('/assets', express.static(path.resolve(__dirname, 'assets')));
app.get('/todo-list', (req, res) => {
    const todoList = [
        { id: 'task1', title: 'Buy Milk', description: 'Remember to buy milk' },
        { id: 'task2', title: 'Go to the gym', description: 'Remember to work out' }
    ];
    return res.json(todoList);
});



