#!/usr/bin/env node
var fs = require('fs');
var path = require('path');
var express = require('express');
var bodyParser = require('body-parser');
var app = express();
var cors = require('express-cors');

// bosy parser needed to parse POST'ed form data
app.use(bodyParser.urlencoded({ extended: true }));

app.use(cors({
    headers : ['X-Requested-With', 'Content-Type', 'Custom-Nick'],
    allowedOrigins: ['127.0.0.1:*', 'localhost:*']
}));

app.get('/data', function (req, res) {
    var json = path.join(__dirname, '../src/json/characters.json');
    var readable = fs.createReadStream(json);
    readable.pipe(res);
});


app.post('/data', function (req, res) {
    res.send(req.body)
});

var server = app.listen(1970, function () {
    console.log('Server running at http://localhost:' + server.address().port)
});