import {Component} from '@angular/core';

/**
 * Component
 */
@Component({
  selector: 'multi-content',
  styles: [`
      .box {
          min-height: 30px;
          border: 5px solid purple;
          display: block;
          margin-bottom: 10px;
      }
  `],
  template: `
      <collapse-it>
          <p class='file'>src/app/misc-examples/components/multi-content/multi-content.ts</p>
          <h4>Multi content projection into named template</h4>

          <div class='box'>
              <code>&lt;ng-content select='[header]'&gt;&lt;/ng-content&gt;</code>
              <ng-content select='[header]'></ng-content>
          </div>

          <div class='box'>
              <code>&lt;ng-content select='[body]'&gt;&lt;/ng-content&gt;</code>
              <p>Content here is generated by a separate emitter-component.</p>
              <ng-content select='[body]'></ng-content>
          </div>
      </collapse-it>
  `
})
export class MultiContentComponent {
}


/**
 * Component
 */
@Component({
  selector: 'multi-content-config',
  template: `
      <multi-content>
          <div header>
              This content is projected into the 'header'.
              The body content below is a separate component.
          </div>
          <emitter-component body></emitter-component>
      </multi-content>
  `
})
export class MultiContentConfigComponent {
}
